### ISSUE TITLE
在哪里能看到你们的技术报告？

### ISSUE THREAD

**Issue by w617156977** [198808xc/OrganSegRSTN#2]
能麻烦给个链接吗？没有找到，谢谢了！
还有就是你的代码是存放在DATA_PATH下面吗？

**Comment by 198808xc** [comment]
感谢你的关注。

正式论文的链接是：
http://openaccess.thecvf.com/content_cvpr_2018/papers/Yu_Recurrent_Saliency_Transformation_CVPR_2018_paper.pdf

代码在OrganSegRSTN/目录下，DATA_PATH下存放所有数据。具体请看README。

祝顺利！
